name: publish-latest-versioned-snapshot.yml
on:
  workflow_call:
    inputs:
      version:
        required: true
        description: "Version of latest DATED Snapshot"
        type: string

jobs:
  update-latest-versioned-snapshot-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Write version to latest-versioned-snapshot file
        run: echo "${{ inputs.version }}" > latest-versioned-snapshot.txt

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          destination_dir: ./misc
          keep_files: true