name: test
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
      - run: |
        sed -i 's#'['fork']''':' https://img.shields.io/badge/latest--snapshot-error-red#'['fork']''':' https://img.shields.io/badge/latest--snapshot-error-green#g' $(find . -name "README.md")