name: test.yaml
on:
  push:
    branches:
      - main

jobs:

  determine-version:
    name: "Determine snapshot version to be published"
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.get-version.outputs.VERSION }}
      STABLE: ${{ steps.get-version.outputs.STABLE }}
    steps:
      - uses: actions/checkout@v5
      - name: "Get version"
        id: get-version
        run: |
          
          echo "VERSION=1.2222" >> "$GITHUB_OUTPUT"
          echo "STABLE=true" >> "$GITHUB_OUTPUT"
          

#          IFS=.- read -r RELEASE_VERSION_MAJOR RELEASE_VERSION_MINOR RELEASE_VERSION_PATCH SNAPSHOT<<<$(grep "version" gradle.properties | awk -F= '{print $2}')

#          if [[ "${{ github.event.workflow_run.event }}" == "schedule" || "${{ inputs.dated_snapshot }}" == "true" ]]; then
#            echo "VERSION=$RELEASE_VERSION_MAJOR.$RELEASE_VERSION_MINOR.$RELEASE_VERSION_PATCH-$(date +"%Y%m%d")-SNAPSHOT" >> "$GITHUB_OUTPUT"
#            echo "STABLE=true" >> "$GITHUB_OUTPUT"
#          else
#            echo "VERSION=$RELEASE_VERSION_MAJOR.$RELEASE_VERSION_MINOR.$RELEASE_VERSION_PATCH-SNAPSHOT" >> "$GITHUB_OUTPUT"
#          fi

  publish-latest-versioned-snapshot:
    name: "Publish latest versioned snapshot in GitHub Pages"
    permissions:
      contents: write
    needs: [determine-version]
    if: ${{ needs.determine-version.outputs.STABLE == 'true' }}
    uses: ./.github/workflows/publish-latest-versioned-snapshot.yml
    secrets: inherit
    with:
      version: ${{ needs.determine-version.outputs.VERSION }}