name: test.yml
on:
  workflow_run:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update version and charts
        uses: actions/checkout@v5
        with:
          version: "0.15.0"
          bump_version: "false"
