name: test
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test:
    steps:
      - name: Update coiso
        shell: bash
        run: |-
          sed -i 's#\[fork\]: https://img.shields.io/badge/latest--snapshot-error-red#\[fork\]: https://img.shields.io/badge/latest--snapshot-error-green#g' README.md
      - name: Commit changes
        id: make-commit
        shell: bash
        run: |
          git add .
          git config user.name "eclipse-tractusx-bot"
          git config user.email "tractusx-bot@eclipse.org"
          git commit --message "Prepare release ${{ inputs.version }}"
          echo "commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT