name: test

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Update badge
        shell: bash
        run: |
          sed -i 's#'['fork']'':'https':''/''/'img'.'shields'.'io'/'badge'/'latest'-'snapshot'-'error'-'red#"ricardo"#g' $(find . -name "README.md")
      - name: Commit changes
        id: make-commit
        shell: bash
        run: |
          git config user.name "sfsfot"
          git config user.email "sda@sda.org"
          git add README.md
          git commit --message "Prepare release " || echo "No changes to commit"
          echo "commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
