name: test
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    run: |
      git config --global user.name "github-actions[bot]"
      git config --global user.email "github-actions[bot]@users.noreply.github.com"
      sed -i 's#\[fork\]: https://img.shields.io/badge/latest--snapshot-error-red#\[fork\]: https://img.shields.io/badge/latest--snapshot-error-green#g' README.md
      git add README.md
      git commit -m "Update fork badge from red to green" || echo "No changes to commit"
      git push