name: test.yml
on:
  workflow_run:
    workflows: [ "Generate DEPENDENCIES file and publish to GitHub pages" ]
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Create Release branch
        run: git checkout -b yeeeeeeeeeeeee

      - name: Version and Chart Updates
        uses: ./.github/actions/update-version-and-charts
        with:
          version: "0.20.0"
          bump_version: "false"

      - name: Push new branch
        run: git push origin yeeeeeeeeeeeee:main

      - uses: actions/checkout@v5
      - name: Create Release branch
        run: git checkout -b kanyeeeeeeeee

      - name: Version and Chart Updates
        uses: ./.github/actions/update-version-and-charts
        with:
          version: "0.21.0"
          bump_version: "false"

      - name: Push new branch
        run: git push origin kanyeeeeeeeee:main
