#################################################################################
#  Copyright (c) 2023 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
#  Copyright (c) 2021,2023 Contributors to the Eclipse Foundation
#
#  See the NOTICE file(s) distributed with this work for additional
#  information regarding copyright ownership.
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#  https://www.apache.org/licenses/LICENSE-2.0.
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations
#  under the License.
#
#  SPDX-License-Identifier: Apache-2.0
#################################################################################


---
name: "Publish Maven Artefacts to Maven Central"

on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        description: 'a semver string denoting the version. Append -SNAPSHOT for snapshots. If omitted, the version is taken from gradle.properties'
      dated:
        type: string
        required: false
  workflow_call:
    inputs:
      version:
        type: string
        required: false
        description: 'a semver string denoting the version. Append -SNAPSHOT for snapshots. If omitted, the version is taken from gradle.properties'
      dated:
        type: string
        required: false

jobs:
  maven-release:
    name: 'Publish all artefacts to MavenCentral'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-java

      - run: |
          echo "Input Version: ${{ inputs.version }}"

          # set the input version in gradle.properties, if passed
          if [ ! -z ${{ inputs.version }} ];
          then
            sed -i 's#^version=.*#version='"${{ inputs.version }}"'#g' $(find . -name "gradle.properties")
            VERSION=${{ inputs.version }}
          fi
          grep version gradle.properties | (echo -n "Publishing using " && cat)

  update-snapshot-badge:
    name: 'Update Snapshot badge in README.md'
    needs: maven-release
    runs-on: ubuntu-latest
    steps:
      - name: Update README badge
        run: |
          echo "maven-release result: '${{ needs.maven-release.result }}'"
          
          # check the needs result (non-empty OR check equality to 'success' if that's what you want)
          if [ -n "${{ needs.maven-release.result }}" ]; then
            # check if inputs.dated is empty
            if [ -z "${{ inputs.dated }}" ]; then
              # On ubuntu (GNU sed) use -i with no empty-suffix
              sed -i "s|^\[fork\]:.*|[fork]:https://img.shields.io/badge/latest--snapshot-${{ inputs.version }}-green|" "./README.md"
              sed -i '' "s|^\[fork\]:.*|[fork]: monitoring-edc-loki-logs|g" $(find . -name "README.md")
              sed -i '' "s|^\[fork\]:.*|[fork]: monitoring-edc-loki-logs|g" $(find . -name "README.md")


            fi
          else
            sed -i "s|^\[fork\]:.*|[fork]:https://img.shields.io/badge/latest--snapshot-ERROR-red|" README.md
          fi
